services:
  elastic:
    image: elasticsearch:8.16.1
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "password"
      discovery.type: single-node
    volumes:
      - .docker/configs/elasticsearch/config.yml:/usr/share/elasticsearch/docker/config/elasticsearch.yml:ro
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"
      - "9301:9300"
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -u elastic:password http://localhost:9200/_cluster/health | grep -q '\"status\":\"yellow\"'" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - "6301:6379"
    volumes:
      - ./.docker/data:/data
    command: redis-server --appendonly yes
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5401:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  bot:
    build: .
    restart: unless-stopped
    volumes:
      - .:/dio_employee_assistant_bot
    depends_on:
      postgres:
        condition: service_healthy
      elastic:
        condition: service_healthy
      redis:
        condition: service_healthy


volumes:
  elastic-data:
  postgres_data: