services:
  elastic:
    image: elasticsearch:8.16.1
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "password"
      discovery.type: single-node
    volumes:
      - .docker/configs/elasticsearch/config.yml:/usr/share/elasticsearch/docker/config/elasticsearch.yml:ro
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"
      - "9301:9300"
  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - "6301:6379"
    volumes:
      - ./.docker/data:/data
    command: redis-server --appendonly yes
    restart: always

  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5401:5432"

  bot:
    build: .
    restart: unless-stopped
    volumes:
      - .:/dio_employee_assistant_bot
    depends_on:
      - postgres
      - elastic
      - redis

volumes:
  elastic-data:
  postgres_data: